// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAqB1Zp0MXWFDWLtEa9-JVSikrpCQPcKI',
    appId: '1:210120469209:web:567a885130b5549f08acc8',
    messagingSenderId: '210120469209',
    projectId: 'tryy-25e25',
    authDomain: 'tryy-25e25.firebaseapp.com',
    storageBucket: 'tryy-25e25.firebasestorage.app',
    measurementId: 'G-VE7VS45F8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbf9APGAsC2PfeOksL4l-x7ie24bOp5-E',
    appId: '1:210120469209:android:93fc8370c579d04108acc8',
    messagingSenderId: '210120469209',
    projectId: 'tryy-25e25',
    storageBucket: 'tryy-25e25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBalg14M-smy3wQVpupk-6DBG00DGky1Zs',
    appId: '1:210120469209:ios:c2fe0fdedfce32d608acc8',
    messagingSenderId: '210120469209',
    projectId: 'tryy-25e25',
    storageBucket: 'tryy-25e25.firebasestorage.app',
    iosBundleId: 'com.example.culture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBalg14M-smy3wQVpupk-6DBG00DGky1Zs',
    appId: '1:210120469209:ios:c2fe0fdedfce32d608acc8',
    messagingSenderId: '210120469209',
    projectId: 'tryy-25e25',
    storageBucket: 'tryy-25e25.firebasestorage.app',
    iosBundleId: 'com.example.culture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAqB1Zp0MXWFDWLtEa9-JVSikrpCQPcKI',
    appId: '1:210120469209:web:f9bd17ece872d0d908acc8',
    messagingSenderId: '210120469209',
    projectId: 'tryy-25e25',
    authDomain: 'tryy-25e25.firebaseapp.com',
    storageBucket: 'tryy-25e25.firebasestorage.app',
    measurementId: 'G-WF08CNF0HM',
  );
}
